### PR TITLE
Plugin: output params file for usage in automation

### PR DESCRIPTION
**Pull request by moolitayer**
Example output:
1 - with prometheus routes:
```
HAWKULAR_ROUTE="hawkular-metrics.10.35.48.12.nip.io"
PROMETHEUS_ALERTS_ROUTE="alerts-prometheus.10.35.48.12.nip.io"
PROMETHEUS_METRICS_ROUTE="prometheus-prometheus.10.35.48.12.nip.io"
OSH_HOST="ocp-master01.10.35.48.11.nip.io"
OSH_TOKEN="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtYW5hZ2VtZW50LWluZnJhIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6Im1hbmFnZW1lbnQtYWRtaW4tdG9rZW4tbjVkc2siLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibWFuYWdlbWVudC1hZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImRiNjE4NjE0LTkxN2QtMTFlNy04N2Q4LTAwMWE0YTE2MjYwYiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDptYW5hZ2VtZW50LWluZnJhOm1hbmFnZW1lbnQtYWRtaW4ifQ.oqWlEvCgRrcaT2V7sS-LIUqp82fgAPgSmzrQiuCiPs_h-u1BQM3A1-vRUd6orT2oq4DuBd1bzQeatoIeC0TrUc0QtHO1W_DL49zknKZ5z2qc3qAghUfDPbg20uHjDkEkMXziDjxTWjkl4vEOAOnnUOYTXo9zn3MUDVfJr5p2tCrekJ8nThq-o1D95kqkMuMEhG88QViYFlMbMWdiquTCDKsJPq5gtgLD-KY_2UXDNoO6ag4Xt65PSzpeEvs2Uzf0YqlCRv2VPEjwHXV3HGkOsI4tYUVbMeAbMeG07kyeFMyxqrow_V11VhnET2ixBjHJ5oN-l_k1YniodnSfSU52rw"
OSH_CERT="-----BEGIN CERTIFICATE-----
MIIC6jCCAdKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
c2hpZnQtc2lnbmVyQDE1MDQ2ODQwNjcwHhcNMTcwOTA2MDc0NzQ2WhcNMjIwOTA1
MDc0NzQ3WjAmMSQwIgYDVQQDDBtvcGVuc2hpZnQtc2lnbmVyQDE1MDQ2ODQwNjcw
ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQD3nuF+vk9XBPp02MZ7nl1m
blnVJ+ocNYBNNwh/Wvcc0s1rHB2EI72wZjxbJ5/+imCzvAp0JaFfCbVRdG1JZ9Q/
ID0fblEZijC1Izd3uhOVORoZ57NDgTsOB3C9bert2CkRsDSM0LS2MiEsM/KaFday
xK5gRHMTfzKXOxATf9/iDnN1zJftOaCkUc7AMc2hq+PGeaTn5ccFzPidRVbh6XNO
8HGHExg2yUSHn/kj+k2qbQ8lawOKeowLuh0+T717+3+i/S3W0wpXjB6PL2T3Qr/4
sqqCMeYJNv+wVyzkNqkfse1fvHi/HkeEvTN8cJZxWQL7AVbZljJm5JaPOPLmb4OZ
AgMBAAGjIzAhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MA0GCSqG
SIb3DQEBCwUAA4IBAQBMGjRejTTQqBT/vznA3Zh5dXxU9bc192rziiZqAnHF8M6r
VF0YMhn5pliYh8sHW8dhwtAauu/l97oEOOVobIlC5NviIoeodBq7XDWSqIUbC4r2
C8cHDFVsXQni5TNmLo8G15rvel0YaMxy6BDgxperGnZ0mZF0kSVxZwS0w+BYzrcm
u9UI3ielKFnpcOghoNpOjhYH9H2d/RL28n1ObndwNY7jenKCq3gGAAqMOvkTvC1A
iGG0SsWjPIfhpo633lmz1rHYGwH5pHV5nfFT1wn3ixPzpZmL/mqCFPUqBnB9+iOZ
5SO/2T7MNMr/5OYZijAU3wEkwa31JV5Swf8r+hwK
-----END CERTIFICATE-----"
```

2 - with out a prometheus routes:
```
HAWKULAR_ROUTE="hawkular-metrics.10.35.48.28.nip.io"
PROMETHEUS_ALERTS_ROUTE=""
PROMETHEUS_METRICS_ROUTE=""
OSH_HOST="ocp-master01.10.35.48.27.nip.io"
OSH_TOKEN="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtYW5hZ2VtZW50LWluZnJhIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6Im1hbmFnZW1lbnQtYWRtaW4tdG9rZW4tbTZ4Z2wiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibWFuYWdlbWVudC1hZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjAzYzUzMjY0LTkyZDgtMTFlNy05Yjg5LTAwMWE0YTE2MjYxYiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDptYW5hZ2VtZW50LWluZnJhOm1hbmFnZW1lbnQtYWRtaW4ifQ.I_bhRcdSvFyG3P_k38lDk2K4rSc51nIgIFj04f4nxUjG7KTf56njrnYeZ9CSMy5h_yXiAub7fHsEERfjf8i9LWD3PTuhuE9PBJqcf5UvVrverpY1s9nd3uQwo4FaezbLfmeuZLypzMYzloJrzqHTsuug9docF_14jaWzyA-HpUbtObsu29r6UprmZg4FIz2zkMisH0CHjf5fvtMes0sEMD1PDZ1oLyejqFYZHZ_lVZ_SoI2fIXr847taLBitBCU9PYH8_oPpaSq0hMOg5Hh0ckgPOe9Gwg29Fr549Ze_nE0uW4YxdFRMw-niG6c4VYVYm6dcyk1Nqrtym9XMF9tMyQ"
OSH_CERT="-----BEGIN CERTIFICATE-----
MIIC6jCCAdKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
c2hpZnQtc2lnbmVyQDE1MDQ2ODQwNjcwHhcNMTcwOTA2MDc0NzQ2WhcNMjIwOTA1
MDc0NzQ3WjAmMSQwIgYDVQQDDBtvcGVuc2hpZnQtc2lnbmVyQDE1MDQ2ODQwNjcw
ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQD3nuF+vk9XBPp02MZ7nl1m
blnVJ+ocNYBNNwh/Wvcc0s1rHB2EI72wZjxbJ5/+imCzvAp0JaFfCbVRdG1JZ9Q/
ID0fblEZijC1Izd3uhOVORoZ57NDgTsOB3C9bert2CkRsDSM0LS2MiEsM/KaFday
xK5gRHMTfzKXOxATf9/iDnN1zJftOaCkUc7AMc2hq+PGeaTn5ccFzPidRVbh6XNO
8HGHExg2yUSHn/kj+k2qbQ8lawOKeowLuh0+T717+3+i/S3W0wpXjB6PL2T3Qr/4
sqqCMeYJNv+wVyzkNqkfse1fvHi/HkeEvTN8cJZxWQL7AVbZljJm5JaPOPLmb4OZ
AgMBAAGjIzAhMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MA0GCSqG
SIb3DQEBCwUAA4IBAQBMGjRejTTQqBT/vznA3Zh5dXxU9bc192rziiZqAnHF8M6r
VF0YMhn5pliYh8sHW8dhwtAauu/l97oEOOVobIlC5NviIoeodBq7XDWSqIUbC4r2
C8cHDFVsXQni5TNmLo8G15rvel0YaMxy6BDgxperGnZ0mZF0kSVxZwS0w+BYzrcm
u9UI3ielKFnpcOghoNpOjhYH9H2d/RL28n1ObndwNY7jenKCq3gGAAqMOvkTvC1A
iGG0SsWjPIfhpo633lmz1rHYGwH5pHV5nfFT1wn3ixPzpZmL/mqCFPUqBnB9+iOZ
5SO/2T7MNMr/5OYZijAU3wEkwa31JV5Swf8r+hwK
-----END CERTIFICATE-----"
```

### CODE REVIEW

**Comment by moolitayer** [comment]
cc @zgalor @simon3z @ilackarms

**Comment by simon3z** [comment]
@moolitayer CA? (Is it harder because multi-line?)

**Comment by moolitayer** [comment]
@simon3z I'm not sure how to do that, what do we expect the result to look like?

**Comment by ilackarms** [comment]
nice

**Comment by simon3z** [comment]
> @simon3z I'm not sure how to do that, what do we expect the result to look like?

@moolitayer it can look like as anything that you can consume. I assume you want to leverage these with ansible.

If you can consume:

```bash
OSH_CA="-----BEGIN CERTIFICATE----- 
MIIC6jCCAdKgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtvcGVu
...
-----END CERTIFICATE-----"
```

then works for me (but be aware that new-lines are not maintained).

Or you can try to add also new-lines at the end `\n`, so then you can `echo -e` when needed.

**Comment by moolitayer** [comment]
Updated example output

**Pull request merged**
