### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by moolitayer**
- Extract LDAP provider to parameter
- Support openshift_install_examples parameter

Tested on http://cm-jenkins.usersys.redhat.com:8080/job/ocp-ansible-jenkins-copy/2/console

### CODE REVIEW

**Comment by moolitayer** [comment]
cc @zgalor @simon3z

**Review by zgalor — APPROVED** [review]
:+1: LGTM

**Comment by moolitayer** [comment]
Build did not deploy Prometheus. No Idea why

**Comment by simon3z** [comment]
:+1:

**Comment by moolitayer** [comment]
I've tested these changes along with ~~3~~ 4 parameter changes:
new parameter: INSTALL_EXAMPLES, default=false
new parameter: LDAP_PROVIDERS, default=[{...}]
changed parameter: ADDITIONAL_INSECURE_REGISTRIES, old default `internal1:8888`, new default `["internal1:8888", "internal2"]`
changed parameter: DEPLOYER_REPO_BRANCH_SPECIFIER, old default `*/master`, new default `master`[1]

**Pull request merged**
