### PR TITLE
Add prometheus

### PR DESCRIPTION
**Pull request by zgalor**
Added the prometheus deploy flag to the inventory file.
It will just be ignored if code base doesn't support it

### CODE REVIEW

**Comment by moolitayer** [comment]
@zgalor we agreed that with each pull request there should be a successful build attached (with openshift-ansible master)

**Comment by zgalor** [comment]
@moolitayer 
http://10.35.48.115:8080/job/ocp-ansible-jenkins/66/console

**Comment by moolitayer** [comment]
> @moolitayer
> http://10.35.48.115:8080/job/ocp-ansible-jenkins/66/console

:+1: Thanks!

**Review by moolitayer — APPROVED** [review]
LGTM :+1:

**Comment by moolitayer** [comment]
cc @simon3z

**Pull request merged**
