### PR TITLE
Remove create router cert param

### PR DESCRIPTION
**Pull request by moolitayer**
This is valid with openshift-ansible >= 3.6.1

### CODE REVIEW

**Comment by moolitayer** [comment]
@simon3z @zgalor please review

**Review by zgalor — APPROVED** [review]
LGTM

**Comment by simon3z** [comment]
@enoodle please review

**Comment by enoodle** [comment]
> This is valid with openshift-ansible >= 3.6.1

Yes,
This is depending on https://github.com/openshift/openshift-ansible/pull/4693 being in the openshift-ansible which I think it is not yet, This is why I opened https://github.com/openshift/openshift-ansible/pull/5042

**Comment by elad661** [comment]
Closing as obsolete.

**Pull request closed without merging**
